version: "3.6"

services:
  postgres:
    build:
      context: ./docker/postgres
    # To enable data persistence, uncomment the following lines
    # volumes:
    #   - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
    ports:
      - 5432:5432
