version: '3.6'

networks:
    web:
        driver: bridge

volumes:
    postgres:
        driver: local

services:
    postgres:
        build:
            context: ./postgres
#        To enable data persistence, uncomment the following lines
#        volumes:
#            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=default
            - POSTGRES_USER=default
            - POSTGRES_PASSWORD=default
        networks:
            - web
        ports:
            - 5432:5432